version: 2.1
orbs:
  cypress: cypress-io/cypress@3.1.2
jobs:
  build:
    docker:
      - image: cimg/node:20.3.0
    steps:
      - checkout
      - run: node --version
      - run: echo "it's working"

  # workflows: # Workflows are a declarative way to orchestrate jobs and their run order.
  test_app:
    jobs:
      - build
      - cypress/run: # Run the cypress/run job from the cypress orb
          package-manager: yarn
          start-command: yarn start # Run the cypress run command in headless mode

