version: 2.1
orbs:
  aws-cli: circleci/aws-cli@4.0.0
  cypress: cypress-io/cypress@3
jobs:
  build_and_test:
    working_directory: ~/circle-ci-s3-deploy
    docker:
      - image: cimg/node:20.3.0
      - image: cypress/base:18.16.0
    steps:
      - checkout
      - run: node --version
      - run: echo "it's working"
      - run:
          name: "Install dependencies"
          command: yarn
      - run:
          name: "Run linting"
          command: yarn lint
      - run:
          name: "Run the app"
          command: yarn start
      - run:
          name: "Run cypress test"
          command: yarn cypress:run
      - run:
          name: "Run build"
          command: yarn build
      - persist_to_workspace:
          root: .
          paths:
            - .
      - run: echo "Jobs are finished"
      - store_test_results:
          path: test-results
  deploy_project:
    executor: aws-cli/default
    steps:
      - attach_workspace:
          at: .
      - aws-cli/setup:
          profile_name: default
      - checkout
      - run:
          name: Upload file to S3
          command: aws s3 sync ./build/ s3://reactcicdtesting --delete

workflows: # Workflows are a declarative way to orchestrate jobs and their run order.
  test_app:
    jobs:
      - build_and_test
      - deploy_project:
          requires:
            - build_and_test
          context: aws-context
