version: 2.1 # Use 2.1 to make use of orbs and other features
orbs: # An orb is a reusable package of CircleCI configuration that you may share
  # across projects, enabling you to create encapsulated, parameterized commands, jobs, and
  # executors that can be used across multiple projects.
  cypress: cypress-io/cypress@3.1.2
# jobs:
#   deploy-job:
#     steps:
#       - add_ssh_keys:
#           fingerprints:
#             - "84:8e:77:2c:ec:f6:1b:d8:a7:f7:a5:12:ea:2d:bc:a4"
workflows: # Workflows are a declarative way to orchestrate jobs and their run order.
  build:
    jobs:
      - cypress/run: # Run the cypress/run job from the cypress orb
          package-manager: yarn
          start-command: yarn start # Run the cypress run command in headless mode

