version: 2.1

jobs:
  build:
    docker:
      - image: cimg/node:20.3.0
    steps:
      - checkout
      - run: node --version
      - run: echo "it's working"
      - run:
          name: "Install dependencies"
          command: yarn
      - run:
          name: "Run linting"
          command: yarn lint
      - run: echo "installation finished"

workflows: # Workflows are a declarative way to orchestrate jobs and their run order.
  test_app:
    jobs:
      - build
      # - cypress/run: # Run the cypress/run job from the cypress orb
      #     package-manager: yarn
      #     start-command: yarn start # Run the cypress run command in headless mode

