version: 2.1
orbs:
  aws-cli: circleci/aws-cli@0.1.18

jobs:
  build:
    working_directory: ~/circle-ci-s3-deploy
    docker:
      - image: cimg/node:20.3.0
    steps:
      - checkout
      - run: node --version
      - run: echo "it's working"
      - run:
          name: "Install dependencies"
          command: yarn
      - run:
          name: "Run linting"
          command: yarn lint
      - run:
          name: "Run build"
          command: yarn build
      - persist_to_workspace:
          root: .
          paths:
            - .
      - run: echo "installation finished"
  test_e2e:
    steps:
      - run: echo "Run cypress"
          # name: "Run cypress"
          # command: yarn cypress:run
  deploy_project:
    executor: aws-cli/default
    steps:
      - attach_workspace:
          at: .
      - aws-cli/setup:
          profile-name: default
      - checkout
      - run:
          name: Upload file to S3
          command: aws s3 sync ./build/ s3://reactcicdtesting --delete

workflows: # Workflows are a declarative way to orchestrate jobs and their run order.
  test_app:
    jobs:
      - build:
          requires:
            - test_e2e
      - deploy_project:
          requires:
            - build
          context: aws-context
