version: 2.1
orbs:
  aws-cli: circleci/aws-cli@0.1.18

jobs:
  build:
    docker:
      - image: cimg/node:20.3.0
    steps:
      - checkout
      - run: node --version
      - run: echo "it's working"
      - run:
          name: "Install dependencies"
          command: yarn
      - run:
          name: "Run linting"
          command: yarn lint
      - run:
          name: "Run build"
          command: yarn build
      - run: echo "installation finished"
  deploy_project:
    executor: aws-cli/default
    steps:
      - attach_workspace:
          at: .
      - aws-cli/setup:
          profile-name: default
      - run:
          name: 'Print working directory'
          command: ls
      - run:
          name: Upload file to S3
          command: aws s3 sync ./build/ s3://reactcicdtesting --delete

workflows: # Workflows are a declarative way to orchestrate jobs and their run order.
  test_app:
    jobs:
      - build
      - deploy_project:
          requires:
            - build
          context: aws-context
